CREATE TABLE
    IS601_Account(
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT NOT NULL UNIQUE,
        account_number VARCHAR(12) UNIQUE NOT NULL,
        balance SMALLINT DEFAULT 0,
        account_type VARCHAR(10),
        created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    )
